{
  "uid" : "4caa3bad4d3165e3",
  "name" : "test_2search",
  "fullName" : "test_suit.test_login.Test_login#test_2search",
  "historyId" : "eec8a0761097f614c2521363acfa7114",
  "time" : {
    "start" : 1640855495690,
    "stop" : 1640855495690,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: type object 'Test_login' has no attribute 'init_driver'",
  "statusTrace" : "cls = <class 'test_suit.test_login.Test_login'>\n\n    @allure.title('打开浏览器')\n    @classmethod\n    def setup_class(cls):\n>       cls.driver = cls.init_driver()\nE       AttributeError: type object 'Test_login' has no attribute 'init_driver'\n\n..\\test_suit\\test_login.py:25: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_xunit_setup_class_fixture_Test_login",
    "time" : {
      "start" : 1640855495598,
      "stop" : 1640855495598,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "AttributeError: type object 'Test_login' has no attribute 'init_driver'\n",
    "statusTrace" : "  File \"E:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 829, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 751, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\xiejun-data\\pyteststudy\\pytest_test_pom\\test_suit\\test_login.py\", line 25, in setup_class\n    cls.driver = cls.init_driver()\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "init_driver",
    "time" : {
      "start" : 1640855494344,
      "stop" : 1640855495598,
      "duration" : 1254
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "查询"
  }, {
    "name" : "feature",
    "value" : "电商项目Web自动化测试"
  }, {
    "name" : "parentSuite",
    "value" : "test_suit"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "Test_login"
  }, {
    "name" : "host",
    "value" : "ENG-469-A"
  }, {
    "name" : "thread",
    "value" : "8404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_suit.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "5800311fa0064309",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression //*[@id=\"search-input\"]1 because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id=\"search-input\"]1' is not a valid XPath expression.\n  (Session info: chrome=96.0.4664.110)",
      "time" : {
        "start" : 1640848602215,
        "stop" : 1640848602291,
        "duration" : 76
      }
    }, {
      "uid" : "40dc9dc70dcc4793",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert 1 == 2",
      "time" : {
        "start" : 1640848467399,
        "stop" : 1640848471732,
        "duration" : 4333
      }
    }, {
      "uid" : "de52f03abaf6162a",
      "status" : "broken",
      "statusDetails" : "TypeError: setup_class() missing 1 required positional argument: 'init_driver'",
      "time" : {
        "start" : 1640848417975,
        "stop" : 1640848417975,
        "duration" : 0
      }
    }, {
      "uid" : "34de1ccde7c48637",
      "status" : "broken",
      "statusDetails" : "TypeError: setup_class() missing 1 required positional argument: 'init_driver'",
      "time" : {
        "start" : 1640848000155,
        "stop" : 1640848000155,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "4caa3bad4d3165e3.json",
  "parameterValues" : [ ]
}