{
  "uid" : "d700754f596f6029",
  "name" : "test_1login[loginlist0]",
  "fullName" : "test_suit.test_login.Test_login#test_1login",
  "historyId" : "2aba1a2878b48362cb0ebf9bb5d46047",
  "time" : {
    "start" : 1640855494342,
    "stop" : 1640855494342,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: type object 'Test_login' has no attribute 'init_driver'",
  "statusTrace" : "cls = <class 'test_suit.test_login.Test_login'>\n\n    @allure.title('打开浏览器')\n    @classmethod\n    def setup_class(cls):\n>       cls.driver = cls.init_driver()\nE       AttributeError: type object 'Test_login' has no attribute 'init_driver'\n\n..\\test_suit\\test_login.py:25: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_xunit_setup_class_fixture_Test_login",
    "time" : {
      "start" : 1640855495598,
      "stop" : 1640855495598,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "AttributeError: type object 'Test_login' has no attribute 'init_driver'\n",
    "statusTrace" : "  File \"E:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 829, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 751, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\xiejun-data\\pyteststudy\\pytest_test_pom\\test_suit\\test_login.py\", line 25, in setup_class\n    cls.driver = cls.init_driver()\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "init_driver",
    "time" : {
      "start" : 1640855494344,
      "stop" : 1640855495598,
      "duration" : 1254
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "登录"
  }, {
    "name" : "feature",
    "value" : "电商项目Web自动化测试"
  }, {
    "name" : "parentSuite",
    "value" : "test_suit"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "Test_login"
  }, {
    "name" : "host",
    "value" : "ENG-469-A"
  }, {
    "name" : "thread",
    "value" : "8404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_suit.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "loginlist",
    "value" : "{'title': '登录失败', 'description': '登录失败的数据，用来测试用户名密码错误', 'username': 'xuzhu666', 'password': 12345}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "255f132e3a67ce62",
      "status" : "passed",
      "time" : {
        "start" : 1640848590133,
        "stop" : 1640848598020,
        "duration" : 7887
      }
    }, {
      "uid" : "866d96b74b7eb31f",
      "status" : "passed",
      "time" : {
        "start" : 1640848455335,
        "stop" : 1640848463246,
        "duration" : 7911
      }
    }, {
      "uid" : "c18c80c88beeba42",
      "status" : "broken",
      "statusDetails" : "TypeError: setup_class() missing 1 required positional argument: 'init_driver'",
      "time" : {
        "start" : 1640848416080,
        "stop" : 1640848416080,
        "duration" : 0
      }
    }, {
      "uid" : "2c25cb9561fff13b",
      "status" : "passed",
      "time" : {
        "start" : 1640848169370,
        "stop" : 1640848176975,
        "duration" : 7605
      }
    }, {
      "uid" : "8355e74c254ee8f3",
      "status" : "broken",
      "statusDetails" : "TypeError: setup_class() missing 1 required positional argument: 'init_driver'",
      "time" : {
        "start" : 1640847998059,
        "stop" : 1640847998059,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "d700754f596f6029.json",
  "parameterValues" : [ "{'title': '登录失败', 'description': '登录失败的数据，用来测试用户名密码错误', 'username': 'xuzhu666', 'password': 12345}" ]
}